# Generated by Django 4.2.10 on 2024-02-08 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CDLM', '0002_employee_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('employee_from', models.CharField(max_length=255)),
                ('employee_to', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
