# Generated by Django 4.2.10 on 2024-02-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDLM', '0003_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='quantity',
        ),
        migrations.AddField(
            model_name='device',
            name='company_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
