# Generated by Django 4.2.10 on 2024-02-09 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CDLM', '0004_remove_lease_quantity_device_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
